=head1 NAME

zg-policy-rc.d - preliminary manpage

=head1 DOCUMENTATION

zg-policy-rc.d is a script which provides flexible handling of the
policy-rc.d script. As invoke-rc.d only looks for policy-rc.d in
/usr/sbin, putting local binaries there would be a policy violation.

Hence, this script.

If the environment variable POLICYRCD is set, the script the variable
pointed to is used. If POLICYRCD is not set,
/etc/zg-policy-rc.d.conf is sourced. /etc/zg-policy-rc.d.conf can
set the POLICYRCD variable.

If invocation of /etc/zg-policy-rc.d.conf does not give a POLICYRCD
value set, the script checks for executeable files in
/usr/local/sbin/policy-rc.d and /etc/policy-rc.d and uses the first
one it finds.

=head1 BUGS

Many. Be prepared to debug.

=head1 AUTHOR

Marc Haber <mh+debian-packages@zugschlus.de>
